import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import { cn } from "@/lib/utils";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lineSeedSansTh = localFont({
  src: [
    {
      path: "../../public/fonts/LineSeedSansTH_W_He.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-line-seed-sans-th",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        geistSans.variable,
        geistMono.variable,
        lineSeedSansTh.variable,
      )}
    >
      <body className="flex min-h-dvh flex-col bg-background [font-family:var(--font-geist-sans)] [--font-heading:var(--font-line-seed-sans-th)] [--font-mono:var(--font-geist-mono)]">
        {children}
      </body>
    </html>
  );
}
